// automatic generated by vnlex.
enum {
	PROD__0 = 0, // -> script
	PROD_array_0 = 17, //array -> '[' ']'
	PROD_array_1 = 18, //array -> '[' value_list ']'
	PROD_item_0 = 19, //item -> @identifier
	PROD_item_1 = 20, //item -> @identifier '=' value
	PROD_item_list_0 = 21, //item_list -> item
	PROD_item_list_1 = 22, //item_list -> item_list item
	PROD_object_0 = 23, //object -> '{' '}'
	PROD_object_1 = 24, //object -> '{' item_list '}'
	PROD_reference_0 = 12, //reference -> '@' @identifier
	PROD_reference_1 = 13, //reference -> @identifier
	PROD_reference_2 = 14, //reference -> @identifier ':' value
	PROD_script_0 = 25, //script -> value_list
	PROD_value_0 = 1, //value -> 'null'
	PROD_value_1 = 2, //value -> 'true'
	PROD_value_2 = 3, //value -> 'false'
	PROD_value_3 = 4, //value -> @integer
	PROD_value_4 = 5, //value -> @long_integer
	PROD_value_5 = 6, //value -> @float
	PROD_value_6 = 7, //value -> @double
	PROD_value_7 = 8, //value -> @string_literal
	PROD_value_8 = 9, //value -> reference
	PROD_value_9 = 10, //value -> array
	PROD_value_10 = 11, //value -> object
	PROD_value_list_0 = 15, //value_list -> value
	PROD_value_list_1 = 16, //value_list -> value_list value
	PROD_COUNT = 26
};
