// automatic generated by vnlex
static _vn_ns::LR_Terminal g_keywordInfo[] = {
	{"false", 1},
	{"null", 2},
	{"true", 3},
	{(const char *)0, 0}
};

static _vn_ns::LR_Terminal g_symbolInfo[] = {
	{",", 1},
	{":", 2},
	{"[", 3},
	{"]", 4},
	{"{", 5},
	{"}", 6},
	{(const char *)0, 0}
};

static _vn_ns::LR_Jump g_state0_jumps[] = {
	_vn_ns::LR_Jump(5, 1),
	_vn_ns::LR_Jump(4, 2),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 3),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state1_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state1_reduction = {
	1, 0, 0
};

static _vn_ns::LR_Jump g_state2_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state2_reduction = {
	1, 20, 5
};

static _vn_ns::LR_Jump g_state3_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 6, 4),
	_vn_ns::LR_Jump(3, 5),
	_vn_ns::LR_Jump(2, 6),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 7),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state4_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state4_reduction = {
	2, 18, 4
};

static _vn_ns::LR_Jump g_state5_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 6, 8),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 1, 9),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state6_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state6_reduction = {
	1, 14, 3
};

static _vn_ns::LR_Jump g_state7_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 2, 10),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state8_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state8_reduction = {
	3, 19, 4
};

static _vn_ns::LR_Jump g_state9_jumps[] = {
	_vn_ns::LR_Jump(2, 11),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 7),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state10_jumps[] = {
	_vn_ns::LR_Jump(6, 12),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 2, 13),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 3, 14),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 1, 15),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 16),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 17),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 18),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 19),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 20),
	_vn_ns::LR_Jump(1, 21),
	_vn_ns::LR_Jump(4, 22),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 3, 23),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 3),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state11_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state11_reduction = {
	3, 15, 3
};

static _vn_ns::LR_Jump g_state12_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state12_reduction = {
	3, 13, 2
};

static _vn_ns::LR_Jump g_state13_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state13_reduction = {
	1, 1, 6
};

static _vn_ns::LR_Jump g_state14_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state14_reduction = {
	1, 2, 6
};

static _vn_ns::LR_Jump g_state15_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state15_reduction = {
	1, 3, 6
};

static _vn_ns::LR_Jump g_state16_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state16_reduction = {
	1, 4, 6
};

static _vn_ns::LR_Jump g_state17_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state17_reduction = {
	1, 5, 6
};

static _vn_ns::LR_Jump g_state18_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state18_reduction = {
	1, 6, 6
};

static _vn_ns::LR_Jump g_state19_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state19_reduction = {
	1, 7, 6
};

static _vn_ns::LR_Jump g_state20_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state20_reduction = {
	1, 8, 6
};

static _vn_ns::LR_Jump g_state21_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state21_reduction = {
	1, 9, 6
};

static _vn_ns::LR_Jump g_state22_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state22_reduction = {
	1, 10, 6
};

static _vn_ns::LR_Jump g_state23_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 4, 24),
	_vn_ns::LR_Jump(7, 25),
	_vn_ns::LR_Jump(6, 26),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 2, 13),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 3, 14),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 1, 15),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 16),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 17),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 18),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 19),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 20),
	_vn_ns::LR_Jump(1, 21),
	_vn_ns::LR_Jump(4, 22),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 3, 23),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 3),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state24_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state24_reduction = {
	2, 16, 1
};

static _vn_ns::LR_Jump g_state25_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 4, 27),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 1, 28),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state26_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state26_reduction = {
	1, 11, 7
};

static _vn_ns::LR_Jump g_state27_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state27_reduction = {
	3, 17, 1
};

static _vn_ns::LR_Jump g_state28_jumps[] = {
	_vn_ns::LR_Jump(6, 29),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 2, 13),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 3, 14),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 1, 15),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 16),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 17),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 18),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 19),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 20),
	_vn_ns::LR_Jump(1, 21),
	_vn_ns::LR_Jump(4, 22),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 3, 23),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 3),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state29_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state29_reduction = {
	3, 12, 7
};

static _vn_ns::LR_State g_states[] = {
	{0, g_state0_jumps, (_vn_ns::LR_Reduction *)0},
	{1, g_state1_jumps, &g_state1_reduction},
	{2, g_state2_jumps, &g_state2_reduction},
	{3, g_state3_jumps, (_vn_ns::LR_Reduction *)0},
	{4, g_state4_jumps, &g_state4_reduction},
	{5, g_state5_jumps, (_vn_ns::LR_Reduction *)0},
	{6, g_state6_jumps, &g_state6_reduction},
	{7, g_state7_jumps, (_vn_ns::LR_Reduction *)0},
	{8, g_state8_jumps, &g_state8_reduction},
	{9, g_state9_jumps, (_vn_ns::LR_Reduction *)0},
	{10, g_state10_jumps, (_vn_ns::LR_Reduction *)0},
	{11, g_state11_jumps, &g_state11_reduction},
	{12, g_state12_jumps, &g_state12_reduction},
	{13, g_state13_jumps, &g_state13_reduction},
	{14, g_state14_jumps, &g_state14_reduction},
	{15, g_state15_jumps, &g_state15_reduction},
	{16, g_state16_jumps, &g_state16_reduction},
	{17, g_state17_jumps, &g_state17_reduction},
	{18, g_state18_jumps, &g_state18_reduction},
	{19, g_state19_jumps, &g_state19_reduction},
	{20, g_state20_jumps, &g_state20_reduction},
	{21, g_state21_jumps, &g_state21_reduction},
	{22, g_state22_jumps, &g_state22_reduction},
	{23, g_state23_jumps, (_vn_ns::LR_Reduction *)0},
	{24, g_state24_jumps, &g_state24_reduction},
	{25, g_state25_jumps, (_vn_ns::LR_Reduction *)0},
	{26, g_state26_jumps, &g_state26_reduction},
	{27, g_state27_jumps, &g_state27_reduction},
	{28, g_state28_jumps, (_vn_ns::LR_Reduction *)0},
	{29, g_state29_jumps, &g_state29_reduction},
	{0xFFFFFFFF, (_vn_ns::LR_Jump *)0, (_vn_ns::LR_Reduction *)0}
};
