// automatic generated by vnlex.
enum {
	PROD__0 = 0, // -> script
	PROD_array_0 = 16, //array -> '[' ']'
	PROD_array_1 = 17, //array -> '[' value_list ']'
	PROD_item_0 = 13, //item -> @string_literal ':' value
	PROD_item_list_0 = 14, //item_list -> item
	PROD_item_list_1 = 15, //item_list -> item_list ',' item
	PROD_object_0 = 18, //object -> '{' '}'
	PROD_object_1 = 19, //object -> '{' item_list '}'
	PROD_script_0 = 20, //script -> object
	PROD_value_0 = 1, //value -> 'null'
	PROD_value_1 = 2, //value -> 'true'
	PROD_value_2 = 3, //value -> 'false'
	PROD_value_3 = 4, //value -> @integer
	PROD_value_4 = 5, //value -> @long_integer
	PROD_value_5 = 6, //value -> @float
	PROD_value_6 = 7, //value -> @double
	PROD_value_7 = 8, //value -> @string_literal
	PROD_value_8 = 9, //value -> array
	PROD_value_9 = 10, //value -> object
	PROD_value_list_0 = 11, //value_list -> value
	PROD_value_list_1 = 12, //value_list -> value_list ',' value
	PROD_COUNT = 21
};
